apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.cron.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.serviceAccount.enabled }}
          serviceAccountName: {{ .Chart.Name }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              {{- if .Values.global.image.registry }}
              image: "{{ .Values.global.image.registry }}/{{ .Values.cron.image.name }}:{{ .Values.cron.image.tag }}"
              {{- else }}
              image: "{{ .Values.cron.image.name }}:{{ .Values.cron.image.tag }}"
              {{- end }}
              imagePullPolicy: Always
              {{- with .Values.cron.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                {{- with .Values.secret.cronitor }}
                - name: CRONITOR_TELEMETRY_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .name }}
                      key: {{ .key }}
                {{- end }}
              {{- if gt (len .Values.cron.env) 0 }}
                {{- toYaml .Values.cron.env | nindent 16 }}
              {{- end }}
          {{- if gt (len .Values.cron.image.pullSecrets) 0 }}
            {{- range .Values.cron.image.pullSecrets }}
          imagePullSecrets:
            - name: {{ . }}
            {{- end }}
          {{- end }}
          restartPolicy: Never