# Cronitor API key secret.
{{- if .Values.secret.cronitor.create }}
  {{- with .Values.secret.cronitor }}
apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ .key }}: {{ .value | b64enc | quote }}
type: {{ .type }}
  {{- end }}
{{- end }}