# Generate all secrets in pullsecrets list.
{{- range $pullSecret := .Values.cron.image.pullSecrets }}
---
apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
  name: {{ $pullSecret.name }}
  namespace: {{ $.Release.Namespace }}
  {{- with $pullSecret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $pullSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  .{{ $.Values.global.docker.secretType }}: {{ $pullSecret.value | quote }}
type: kubernetes.io/{{ $.Values.global.docker.secretType }}
{{- end }}
---
# Cronitor API key secret.
{{- with .Values.secret.cronitor }}
apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ .key }}: {{ .value | b64enc | quote }}
type: {{ .type }}
{{- end }}