apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: {{ .Values.cron.image.name }}:{{ .Values.cron.image.tag }}
              imagePullPolicy: Always
              {{- with .Values.cron.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: CRONITOR_TELEMETRY_KEY
                  valueFrom:
                    secretKeyRef:
                      name: cronitor
                      key: CRONITOR_TELEMETRY_KEY
              {{- if .Values.cron.env }}
                {{- toYaml .Values.cron.env | nindent 16 }}
              {{- end }}
          {{- with .Values.cron.image.pullSecrets }}
          imagePullSecrets:
            {{ toYaml . }}
          {{- end }}
          restartPolicy: OnFailure