apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.serviceAccount.enabled }}
          serviceAccountName: {{ .Chart.Name }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.global.docker.registry }}/{{ .Values.cron.image.name }}:{{ .Values.cron.image.tag }}"
              imagePullPolicy: Always
              {{- with .Values.cron.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: CRONITOR_TELEMETRY_KEY
                  valueFrom:
                    secretKeyRef:
                      name: cronitor
                      key: CRONITOR_TELEMETRY_KEY
              {{- if gt (len .Values.cron.env) 0 }}
                {{- toYaml .Values.cron.env | nindent 16 }}
              {{- end }}
          {{- if gt (len .Values.cron.image.pullSecrets) 0 }}
            {{- range .Values.cron.image.pullSecrets }}
          imagePullSecrets:
            - name: {{ .name }}
            {{- end }}
          {{- end }}
          restartPolicy: Never