{{- range $pullSecret := .Values.cron.image.pullSecrets }}
---
apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
  name: {{ $pullSecret.name }}
  namespace: {{ $.Release.Namespace }}
  {{- with $pullSecret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $pullSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  .{{ $.Values.global.docker.secretType }}: {{ $pullSecret.value | quote }}
type: {{ $.Values.global.docker.secretType }}
{{- end }}