version: 2.1

setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.8.1
  general: premiscale/general@dev:6db0ff051999955508bd1cdb04aaecb3091976d8
  slack: circleci/slack@4.13.2


workflows:
  cluster-checkin:
    jobs:
      # Development branches

      - dynamic/continue:
          context: circleci
          base-revision: master

      # On tag

      - slack/on-hold:
          context: slack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          context:
            - github
            - circleci
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/docker-ecr:
          name: docker [cluster-checkin] [tag]
          image-name: cluster-checkin
          tag: $CIRCLE_TAG
          context:
            - aws-development
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/docker-hub:
          name: dockerhub [cluster-checkin] [tag]
          image-name: cluster-checkin
          tag: $CIRCLE_TAG
          context:
            - dockerhub
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-release-nexus:
          name: helm build and push [helm/cluster-checkin] [tag]
          context: nexus
          repo: $HELM_REPOSITORY_URL
          version: $CIRCLE_TAG
          image-tag: $CIRCLE_TAG
          image-tag-path: .cron.image.tag
          requires:
            - docker [cluster-checkin] [tag]
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-upgrade:
          name: helm upgrade install [helm/cluster-checkin] [tag]
          cluster: $CHELSEA_CLUSTER
          namespace: crons
          repo: $HELM_REPOSITORY_URL
          additional-values: |
            --set global.image.registry="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/release" --set cron.image.pullSecrets[0]=ecr-docker-registry --set cron.env[0].name=CLUSTER_ID,cron.env[0].value="$LOFT_CHELSEA_CLUSTER_ID"
          requires:
            - helm build and push [helm/cluster-checkin] [tag]
            - docker [cluster-checkin] [tag]
          context:
            - kubeconfig
            - aws-development
            - nexus
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/