version: 2.1

setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.7.1
  general: bjd2385/general@0.7.5
  slack: circleci/slack@4.12.5


workflows:
  cluster-checkin:
    jobs:
      # Development branches

      - dynamic/continue:
          context: circleci
          default-branch: master

      # On tag

      - slack/on-hold:
          context: slack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          requires:
            - slack/on-hold
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/docker-nexus:
          name: docker [cluster-checkin] [tag]
          image-name: cluster-checkin
          context: nexus
          path: .
          nexus-domain: $DOCKER_DOMAIN
          tag: $CIRCLE_TAG
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-release-nexus:
          name: helm build and push [helm/] [tag]
          context: nexus
          repo: $HELM_REPOSITORY_URL
          version: $CIRCLE_TAG
          image-tag: $CIRCLE_TAG
          # Uses https://mikefarah.gitbook.io/yq/operators/env-variable-operators#dynamically-update-a-path-from-an-environment-variable
          image-tag-path: .cron.image.tag
          requires:
            - docker [cluster-checkin] [tag]
          filters:
            branches:
              ignore:
                - master

      - general/helm-upgrade:
          name: helm upgrade install [helm/cluster-checkin] [tag]
          cluster: $CHELSEA_CLUSTER
          namespace: crons
          repo: $HELM_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          additional-values: |
            --set global.image.registry="$REPO_DOMAIN" --set global.registry="$DOCKER_DOMAIN" --set cron.image.pullSecrets[0]=nexus-docker-registry
          requires:
            - helm build and push [helm/] [tag]
            - docker [cluster-checkin] [tag]
          context:
            - kubeconfig
            - nexus
          filters:
            branches:
              ignore:
                - master