version: 2.1

setup: true


executors: {}


orbs:
  dynamic: bjd2385/dynamic-continuation@3.7.1


workflows:
  cluster-checkin:
    jobs:
      # Development branches

      - dynamic/continue:
          context: circleci

      # On tag

      - slack/on-hold:
          context: slack
          requires:
            - general/orb-pack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          requires:
            - slack/on-hold
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/