version: 2.1


orbs:
  general: bjd2385/general@0.7.5


workflows:
  helm:
    jobs:
      - general/helm-lint:
          name: helm lint [helm/]
          chart-path: helm/$CIRCLE_PROJECT_REPONAME

      # develop branches

      - general/docker-nexus:
          name: docker [cluster-checkin] [develop]
          image-name: cluster-checkin
          context: nexus
          requires:
            - helm lint [helm/]
          path: .
          nexus-domain: $DOCKER_DEVELOP_DOMAIN
          tag: 0.0.<< pipeline.number >>
          filters:
            branches:
              ignore:
                - master

      - general/helm-release-nexus:
          name: helm build and push [helm/] [develop]
          context: nexus
          repo: $HELM_DEVELOP_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          image-tag: 0.0.<< pipeline.number >>
          # Uses https://mikefarah.gitbook.io/yq/operators/env-variable-operators#dynamically-update-a-path-from-an-environment-variable
          image-tag-path: .cron.image.tag
          requires:
            - helm lint [helm/]
            - docker [cluster-checkin] [develop]
          filters:
            branches:
              ignore:
                - master

      - general/helm-upgrade:
          name: helm upgrade install [helm/cluster-checkin] [develop]
          cluster: $CHELSEA_CLUSTER
          namespace: crons
          repo: $HELM_DEVELOP_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          additional-values: |
            --set global.image.registry="$REPO_DOMAIN" --set global.registry="$DOCKER_DEVELOP_DOMAIN"
          requires:
            - helm build and push [helm/] [develop]
            - docker [cluster-checkin] [develop]
          context:
            - kubeconfig
            - nexus
          filters:
            branches:
              ignore:
                - master

      # master branch

      - general/docker-nexus:
          name: docker [cluster-checkin] [master]
          image-name: cluster-checkin
          context: nexus
          requires:
            - helm lint [helm/]
          path: .
          nexus-domain: $DOCKER_MASTER_DOMAIN
          tag: 0.0.<< pipeline.number >>
          filters:
            branches:
              only:
                - master

      - general/helm-release-nexus:
          name: helm build and push [helm/] [master]
          context: nexus
          repo: $HELM_MASTER_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          image-tag: 0.0.<< pipeline.number >>
          # Uses https://mikefarah.gitbook.io/yq/operators/env-variable-operators#dynamically-update-a-path-from-an-environment-variable
          # image-tag-path: .[env(CIRCLE_PROJECT_REPONAME)].image.tag
          image-tag-path: .cron.image.tag
          requires:
            - helm lint [helm/]
            - docker [cluster-checkin] [master]
          filters:
            branches:
              only:
                - master

      - general/helm-upgrade:
          name: helm upgrade install [helm/] [master]
          cluster: $CHELSEA_CLUSTER
          namespace: crons
          repo: $HELM_MASTER_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          additional-values: |
            --set global.image.registry="$REPO_DOMAIN" --set global.registry="$DOCKER_MASTER_DOMAIN"
          requires:
            - helm build and push [helm/] [master]
            - docker [cluster-checkin] [master]
          context:
            - kubeconfig
            - nexus
          filters:
            branches:
              only:
                - master