version: 2.1


orbs:
  general: premiscale/general@dev:31c8539771afb5505ef3258f78ea9b448bb7ae1b


workflows:
  helm:
    jobs:
      - general/helm-lint:
          name: helm lint [helm/cluster-checkin]
          chart-path: helm/$CIRCLE_PROJECT_REPONAME

      # develop

      - general/docker-ecr:
          name: docker [cluster-checkin] [develop]
          image-name: cluster-checkin
          branch-tag: true
          context:
            - aws-development
          requires:
            - helm lint [helm/cluster-checkin]
          path: .
          tag: 0.0.<< pipeline.number >>
          filters:
            branches:
              ignore:
                - master

      - general/helm-release-ecr:
          name: helm build and push [helm/cluster-checkin] [develop]
          context:
            - aws-development
          version: 0.0.<< pipeline.number >>
          image-tag: 0.0.<< pipeline.number >>
          image-tag-path: .cron.image.tag
          requires:
            - helm lint [helm/cluster-checkin]
            - docker [cluster-checkin] [develop]
          filters:
            branches:
              ignore:
                - master

      - general/helm-upgrade:
          name: helm upgrade install [helm/cluster-checkin] [develop]
          cluster: $CHELSEA_CLUSTER
          namespace: crons
          repo: $HELM_DEVELOP_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          additional-values: |
            --set global.image.registry="$DOCKER_DEVELOP_DOMAIN" --set cron.image.pullSecrets[0]=nexus-docker-registry --set cron.env[0].name=CLUSTER_ID,cron.env[0].value="$LOFT_CHELSEA_CLUSTER_ID"
          requires:
            - helm build and push [helm/cluster-checkin] [develop]
            - docker [cluster-checkin] [develop]
          context:
            - kubeconfig
            - nexus
          filters:
            branches:
              ignore:
                - master

      # master

      - general/docker-ecr:
          name: docker [cluster-checkin] [master]
          image-name: cluster-checkin
          branch-tag: true
          context:
            - aws-development
          requires:
            - helm lint [helm/cluster-checkin]
          path: .
          tag: 0.0.<< pipeline.number >>
          filters:
            branches:
              only:
                - master

      - general/helm-release-ecr:
          name: helm build and push [helm/cluster-checkin] [master]
          context:
            - aws-development
          repo: $HELM_MASTER_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          image-tag: 0.0.<< pipeline.number >>
          image-tag-path: .cron.image.tag
          requires:
            - helm lint [helm/cluster-checkin]
            - docker [cluster-checkin] [master]
          filters:
            branches:
              only:
                - master

      - general/helm-upgrade:
          name: helm upgrade install [helm/cluster-checkin] [master]
          cluster: $CHELSEA_CLUSTER
          namespace: crons
          repo: $HELM_MASTER_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          additional-values: |
            --set global.image.registry="$DOCKER_MASTER_DOMAIN" --set cron.image.pullSecrets[0]=nexus-docker-registry --set cron.env[0].name=CLUSTER_ID,cron.env[0].value="$LOFT_CHELSEA_CLUSTER_ID"
          requires:
            - helm build and push [helm/cluster-checkin] [master]
            - docker [cluster-checkin] [master]
          context:
            - kubeconfig
            - nexus
          filters:
            branches:
              only:
                - master