global:
  storageclass: longhorn
  docker:
    registry: ''
    secretType: dockerconfigjson

secret:
  cronitor:
    create: false
    name: cronitor
    key: CRONITOR_TELEMETRY_KEY
    type: Opaque
    value: ""

cron:
  # Run every 10 minutes. An alert is configured to be thrown in @Devops & Tooling if there are two consecutive failures.
  schedule: '*/10 * * * *'

  image:
    name: cluster-cronitor
    tag: 1.0.0
    pullSecrets: []

  # Specify additional environment variables. Must be a list of valid podspec env vars.
  env:
    - name: CLUSTER_ID
      value: ""

  resources:
    requests:
      memory: 125Mi
      cpu: 0.1
    limits:
      memory: 125Mi
      cpu: 0.25

  securityContext:
    runAsUser: 1001

  annotations: {}
  labels: {}


serviceAccount:
  enabled: true

  annotations: {}
  labels: {}

  clusterRole:
    labels: {}
    annotations: {}
  clusterRoleBinding:
    labels: {}
    annotations: {}